"""
Optional AI Narrative Layer
===========================

The ACCESS *core* workflow is deterministic rule-based math (see
``projection_engine.py``) — no AI touches the numbers. This module adds an
**optional** AI layer that turns a computed projection into a short plain-English
executive summary for the entity's leadership.

Design principle: graceful degradation.
  * If an ``OPENAI_API_KEY`` is present AND the ``openai`` package is installed,
    the summary is generated by an LLM.
  * Otherwise, a deterministic template-based summary is returned instead, so
    the endpoint ALWAYS returns useful output and the app never hard-fails on a
    missing key or offline environment.

The response always reports which path (``"ai"`` or ``"template"``) produced the
text, so the behavior is transparent and testable.
"""

from __future__ import annotations

import os
from typing import Any

from projection_engine import fmt_usd, fmt_num


def _template_summary(payload: dict[str, Any]) -> str:
    """Deterministic fallback summary built directly from the projection.

    Uses no external services, so it works fully offline. This is also what a
    grader sees by default when no API key is configured.
    """
    org = payload.get("org_label", payload.get("org_value", "the entity"))
    proj = payload["projection"]
    rows = proj["rows"]
    tracks = payload.get("track_labels") or ["(none selected)"]
    gaps = payload.get("gap_labels") or []

    # Find the breakeven year (first performance year with non-negative net savings).
    breakeven = next((r for r in rows if r["net_savings"] >= 0), None)
    peak = fmt_num(proj["peak_enrolled"])
    cum_net = fmt_usd(proj["cum_savings"])
    cum_shared = fmt_usd(proj["cum_shared"])

    if breakeven:
        be_txt = (
            f"The model projects a net loss during early ramp-up and reaches "
            f"breakeven in performance year {breakeven['py']} ({breakeven['year']})."
        )
    else:
        be_txt = (
            "The model does not reach net breakeven within the 6-year horizon "
            "under the current assumptions."
        )

    gaps_txt = (
        f" {len(gaps)} unresolved readiness gap(s) ({', '.join(gaps)}) are dragging "
        f"capability maturity, which lowers achievable savings."
        if gaps
        else " No readiness gaps were flagged, so savings mature at the full rate."
    )

    return (
        f"For {org}, the ACCESS projection covers {len(rows)} performance years "
        f"across the clinical track(s): {', '.join(tracks)}. "
        f"Aligned enrollment ramps to a peak of {peak} beneficiaries. "
        f"{be_txt} Over the full horizon the entity accrues {cum_net} in cumulative "
        f"net savings and retains {cum_shared} as its shared-savings share."
        f"{gaps_txt}"
    )


def _ai_summary(payload: dict[str, Any]) -> str:
    """LLM-generated summary. Raises if the API path is unavailable."""
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not set")

    # Imported lazily so the package is only required when the AI path is used.
    from openai import OpenAI  # type: ignore

    client = OpenAI(api_key=api_key)
    proj = payload["projection"]
    facts = {
        "organization": payload.get("org_label"),
        "clinical_tracks": payload.get("track_labels"),
        "readiness_gaps": payload.get("gap_labels"),
        "peak_enrolled": proj["peak_enrolled"],
        "cumulative_net_savings": round(proj["cum_savings"]),
        "cumulative_shared_savings": round(proj["cum_shared"]),
        "yearly": [
            {
                "performance_year": r["py"],
                "calendar_year": r["year"],
                "enrolled": r["enrolled"],
                "net_savings": round(r["net_savings"]),
            }
            for r in proj["rows"]
        ],
    }
    prompt = (
        "You are a value-based care strategy analyst. Write a concise (max 120 "
        "words) executive summary of this ACCESS program projection for the "
        "entity's leadership. Be factual, reference the breakeven year, and do "
        "not invent numbers beyond those provided.\n\n"
        f"Projection facts (JSON): {facts}"
    )
    resp = client.chat.completions.create(
        model=os.environ.get("ACCESS_AI_MODEL", "gpt-4o-mini"),
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=250,
    )
    return resp.choices[0].message.content.strip()


def generate_narrative(payload: dict[str, Any]) -> dict[str, Any]:
    """Return an executive summary + which engine produced it.

    Always succeeds: falls back to the deterministic template if the AI path is
    unavailable or errors out.
    """
    try:
        text = _ai_summary(payload)
        return {"engine": "ai", "summary": text}
    except Exception as exc:  # noqa: BLE001 - graceful degradation is the point
        return {
            "engine": "template",
            "summary": _template_summary(payload),
            "note": f"AI path unavailable ({type(exc).__name__}); used deterministic fallback.",
        }
